version: '3'

services:
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: panel
      MYSQL_USER: panel
      MYSQL_PASSWORD: 123456789
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis
    environment:
      REDIS_PASSWORD: 123456789
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: 123456789
    ports:
      - "8080:80"
    depends_on:
      - mariadb

volumes:
  mariadb_data:
  redis_data:
